# BUILD Settings:
# ##############################################################################
[build]
  publish = "public"
  functions = "lambda"

[dev]
  publish = "public"
  port = 64946
  autolaunch = true

# HEADERS - BASIC AUTH
# ##############################################################################
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Credentials = "true"
    Content-Security-Policy = "form-action https:; frame-src *.stanford.edu *.netlify.app"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"
    Permissions-Policy = "vibrate=(), geolocation=(), midi=(), notifications=(), push=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), speaker=()"

# REDIRECTS
# ##############################################################################

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  [redirects.headers]
    Cache-Control = 'no-store, no-cache, must-revalidate, proxy-revalidate'
    Pragma = 'no-cache'
    Expires = '0'
    Surrogate-Control = 'no-store'