# BUILD Settings:
# ##############################################################################
[build]
  publish = "public"
  functions = "lambda"

[dev]
  publish = "public"
  port = 64946
  autolaunch = true

# HEADERS - BASIC AUTH
# ##############################################################################
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "form-action https:; frame-src *.stanford.edu *.storyblok.com"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"
    Permissions-Policy = "vibrate=(), geolocation=(), midi=(), notifications=(), push=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), speaker=(), vibrate=(), fullscreen=()"

# REDIRECTS
# ##############################################################################

[[redirects]]
  from = "/a/*"
  to = "https://a.storyblok.com/:splat"
  status = 200

[[redirects]]
  from = "/i/*"
  to = "https://img2.storyblok.com/:splat"
  status = 200